using System;
using System.Linq;

namespace EntityFrameworkExample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var database = new northwndEntities())
            {
                // If you leave this line in you can see the SQL generated by the query in the Visual studio output window
                // View -> Output, Ctrl + W, O
                database.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);

                var products = database.Products.Where(product => product.UnitPrice > 50);

                foreach (var product in products)
                {
                    Console.WriteLine(product.ProductName + " : " + product.UnitPrice);
                }
            }

            Console.ReadLine();
        }
    }
}